server:
  port: 8181

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    database: 0
    password: 123456