spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1ms
    database: 0

server:
  port: 8080
  servlet:
    context-path: /

breakpoint:
  upload:
    dir: D:/data0/uploads/
    #1024*1024=1 048 576,10M=10485760
    chunkSize: 10485760

